[profile.default]
solc = "0.8.16"
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
ffi = true
fs_permissions = [
	{ access = "read-write", path = ".forge-snapshots/"},
	{ access = "read", path = "out/"},
	{ access = "read", path = "script/input/"},
]
optimizer_runs = 1_000_000
verbosity = 3

[profile.script]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
